---
name: Approval Single Request
about: Single request, requires approval
title: "Approval Single Request"
labels: ["approval_request", "approval_single_request"]
projects: ["PyLadiesGermany/2"]
assignees: 
- sleepypioneer
- laysauchoa
- discombobulateme
- pga99
- terezaif
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a request for funds. Please fill in the information below. If this is your first request we recommend reading the documentation in this repository beforehand. ***Note that only existing chapters or new chapters who have held at least one event and are known to the PyLadies Germany group may submit requests.***

        This type of request **requires approval**, this means that once submitted you must wait for approval before making the purchase. As soon as the request is approved you can go ahead and submit the receipt for reimbursement. Reimbursement can be expected within.

        After opening the ISSUE a Slack message will be posted on the global PyLadies Slack in channel [#city-germany-pysv-fund](https://pyladies.slack.com/archives/C06B761RX6X).

  - type: input
    id: chapter_name
    attributes:
      label: Chapter Name
      description: "Please enter the name of your chapter"
      placeholder: "PyLadies Germany"
    validations:
      required: true
  - type: checkboxes
    id: add_chapter_name_label
    attributes:
      label: Add chapter name as a label
      description: "Check to confirm you have added the chapter name as a label"
      options:
        - label: "confrimed"
          required: true
  - type: input
    id: requester_name
    attributes:
      label: Name of person submitting request
      description: "Please enter your name"
      placeholder: "Jane Doe"
    validations:
      required: true
  - type: input
    id: ammount_requested
    attributes:
      label: Amount in EURs being requested
      description: "Please enter the amount in EURs being requested"
      placeholder: "100"
    validations:
      required: true
  - type: textarea
    id: reason_for_request
    attributes:
      label: Reason for request
      description: "What the money will be spent on - this will be used for reporting"
      placeholder: "This will be used to pay for the catering for our next event"
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: "Any additional information you would like to provide"
      placeholder: "We have already received a quote from the caterer"
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Approvals
        *Two approvals are required for this request to be approved. Please add the label `approved` to this issue once there are two approvals.*

        - [ ] Approval 1: <name-of-approver>
        - [ ] Approval 2: <name-of-approver>

        ## Post Approval
        **Invoice/Receipt submitted to the PySV:**
        - [ ] Email your invoice to: [invoice@python-verband.org](mailto:invoice@python-verband.org)
        - [ ] I have put pyladies@python-verband.org in CC (or sent a copy)
        - [ ] Add the label `invoice submitted` to this issue
        - [ ] Once the invoice has been paid, add the label `invoice_paid` to this issue & move issue to completed requests

        **Additional Information:**

