---
name: "[<TOTAL_AMOUNT> EUR]: Instant Approval Request"
description: Request for an item on our instant approval list (see below)
title: "Instant Approval Request"
labels: ["approval_request", "instant_approval"]
assignees: 
- sleepypioneer
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a request for funds. Please fill in the information below. If this is your first request we recommend reading the documentation in this repository beforehand. ***Note that only existing chapters or new chapters who have held at least one event and are known to the PyLadies Germany group may submit requests.***

        This type of request does not require approval (but is **restricted to certain items**, if you are unsure first check the guidelines and ask in Slack), which means you can go ahead and submit the receipt for reimbursement. Reimbursement can be expected in 14 days. 

        After opening the ISSUE a Slack message will be posted on the global PyLadies Slack in channel [#city-germany-pysv-fund](https://pyladies.slack.com/archives/C06B761RX6X).
  - type: input
    id: chapter_name
    attributes:
      label: Chapter Name
      description: "Please enter the name of your chapter"
      placeholder: "PyLadies Germany"
    validations:
      required: true
  - type: checkboxes
    id: add_chapter_name_label
    attributes:
      label: Add chapter name as a label
      description: "Check to confirm you have added the chapter name as a label"
      options:
        - label: "confrimed"
          required: true
  - type: input
    id: requester_name
    attributes:
      label: Name of person submitting request
      description: "Please enter your name"
      placeholder: "Jane Doe"
    validations:
      required: true
  - type: input
    id: ammount_requested
    attributes:
      label: Amount in EURs being requested
      description: "Please enter the amount in EURs being requested"
      placeholder: "100"
    validations:
      required: true
  - type: checkboxes
    id: item_requested
    attributes:
      label: Item being requested
      description: "Please select the item being requested"
      options:
        - label: "Up to 200 EUR for stickers per chapter per calendar year"
          required: true
        - label: "A roll-up banner (one-time purchase) for a chapter"
          required: true
        - label: "Shared subscriptions - i.e. Restream/ Lastpass (these subscriptions should have been agreed upon by the chapters beforehand)"
          required: true
  - type: textarea
    id: item_details
    attributes:
      label: Item details
      description: "Add additional details - these will be used for reporting"
      placeholder: "We will use the stickers to promote our chapter at events"
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: "Any additional information you would like to provide"
      placeholder: "We are making a group order with another PyLadies Chapter"
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Post Approval
        **Invoice/Receipt submitted to the PySV:**
        - [ ] Email your invoice to: [invoice@python-verband.org](mailto:invoice@python-verband.org) with pyladies@python-verband.org in CC (you can find a template email in this [repo](./Docs/email_templates.md)).
        - [ ] Add the label `invoice submitted` to this issue
        - [ ] Once the invoice has been paid, add the label `invoice_paid` to this issue & move issue to completed requests

        **Additional Information:**

